name: Build CCExtractor on Linux

on:
  workflow_dispatch:
  push:
    paths:
    - '.github/workflows/build_linux.yml'
    - '**.c'
    - '**.h'
    - '**Makefile**'
    - 'linux/**'
    - 'package_creators/**'
    - 'src/rust/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
    - '.github/workflows/build_linux.yml'
    - '**.c'
    - '**.h'
    - '**Makefile**'
    - 'linux/**'
    - 'package_creators/**'
    - 'src/rust/**'
jobs:
  build_shell:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt update && sudo apt-get install libgpac-dev libtesseract-dev build-essential
    - uses: actions/checkout@v4
    - name: mkdir
      run: mkdir build
    - name: to so
      working-directory: ./linux
      run: ar -x libpac.a && gcc -shared *.o -o libpac.so
    - name: copy
      run: sudo cp libpac.so /usr/lib
      working-directory: ./linux
    - name: cmake
      run: cmake ../src
      working-directory: ./build
    - name: build
      run: make -j$(noproc)
      working-directory: ./build
    - name: Display version information
      run: ./ccextractor --version
      working-directory: ./build
    - uses: actions/upload-artifact@v4
      with:
        name: CCExtractor Linux build
        path: ./build

  